POST https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=AIzaSyBUaMXxElcQZFs4eKSjoe-f1Gn2lWy6QaU
Content-Type: application/json

{
  "idToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjI4Y2M2MzEyZWVkYjI1MzIwMDQyMjI4MWE4MTQ4N2UyYTkzMjJhOTIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbW92aWUtYXBwLTY3NGMzIiwiYXVkIjoibW92aWUtYXBwLTY3NGMzIiwiYXV0aF90aW1lIjoxNTY0NTY2OTQ2LCJ1c2VyX2lkIjoiZHhsWnl2WDVVYWViWkFZbWZhMGNVMzB6UTJCMiIsInN1YiI6ImR4bFp5dlg1VWFlYlpBWW1mYTBjVTMwelEyQjIiLCJpYXQiOjE1NjQ1NjY5NDYsImV4cCI6MTU2NDU3MDU0NiwiZW1haWwiOiJsdXVraW1raGFuaDMxMTJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibHV1a2lta2hhbmgzMTEyQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.nCv5ls3w2Il_CVoLYLi-dHI-syxFt3PTQuoJ1LLm5VksKZRyNvrn2gWeiqlG9jC1caEomFKw8_VT8LjVodV6TFr0K7vCak6ZnmkRV5LHk6CMDV_7IEwONKdWixJ1ArHbtIZdXd1to6NE10rLKVdQTtAzKPn6Q-ukSJpPbR-QMdPwAq_e7sbcgB3H1X5IcJ_zEMpaZJwv45V23NU0uFK6PHXVGgngY4KA6jzt7U2IO0DHkW3a4Bl8u22DNokJhjQfLFZBe4y6DoF2qJQa9Sil86GlfuPQSfSnRQD8ynLYS3ClLUgRHn4JTWkPUcJwvGsql7qvg2jVwAUKF4z7Xx_9iA"
}
